VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
IMG ?= quay.io/bapalm/bps-operator:$(VERSION)
OPERATOR_NAMESPACE ?= bps-operator-system
TEST_NAMESPACE ?= bps-test
KIND_CLUSTER_NAME ?= kind

# Use oc if available, fall back to kubectl
KUBECTL ?= $(shell command -v oc >/dev/null 2>&1 && echo oc || echo kubectl)

.PHONY: build
build:
	go build -o bin/manager ./cmd/

.PHONY: test
test:
	go test ./... -coverprofile cover.out

.PHONY: lint
lint:
	golangci-lint run ./...

.PHONY: fmt
fmt:
	go fmt ./...

.PHONY: vet
vet:
	go vet ./...

.PHONY: generate
generate:
	controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."

.PHONY: manifests
manifests:
	controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases

.PHONY: test-e2e
test-e2e: build-image ## Run e2e tests against a Kind cluster
	@echo "Loading image into Kind cluster..."
	kind load docker-image $(IMG) --name $(KIND_CLUSTER_NAME)
	$(MAKE) deploy
	$(KUBECTL) set image deployment/bps-operator-controller-manager manager=$(IMG) -n $(OPERATOR_NAMESPACE)
	$(KUBECTL) patch deployment bps-operator-controller-manager -n $(OPERATOR_NAMESPACE) \
		-p '{"spec":{"template":{"spec":{"containers":[{"name":"manager","imagePullPolicy":"IfNotPresent"}]}}}}'
	@echo "Waiting for operator to be ready..."
	$(KUBECTL) rollout status deployment/bps-operator-controller-manager -n $(OPERATOR_NAMESPACE) --timeout=120s
	$(KUBECTL) apply -f config/samples/test-workloads.yaml
	$(KUBECTL) wait --for=jsonpath='{.status.phase}'=Active namespace/$(TEST_NAMESPACE) --timeout=10s
	$(KUBECTL) apply -f config/samples/scanner_bps_test.yaml
	@echo "Waiting for scan to complete..."
	@for i in $$(seq 1 90); do \
		PHASE=$$($(KUBECTL) get bestpracticescanners test-scanner -n $(TEST_NAMESPACE) -o jsonpath='{.status.phase}' 2>/dev/null); \
		if [ "$$PHASE" = "Completed" ]; then echo "Scan completed."; break; fi; \
		if [ $$i -eq 90 ]; then \
			echo "Timed out waiting for scan (phase: $$PHASE)"; \
			echo "=== Operator Logs ==="; \
			$(KUBECTL) logs deployment/bps-operator-controller-manager -n $(OPERATOR_NAMESPACE) --tail=50 2>/dev/null || true; \
			echo "=== Scanner Status ==="; \
			$(KUBECTL) get bestpracticescanners test-scanner -n $(TEST_NAMESPACE) -o yaml 2>/dev/null || true; \
			echo "=== Pod Status ==="; \
			$(KUBECTL) get pods -A 2>/dev/null || true; \
			exit 1; \
		fi; \
		sleep 2; \
	done
	@echo "=== E2E Results ==="
	@$(KUBECTL) get bestpracticeresults -n $(TEST_NAMESPACE)
	@echo ""
	@echo "=== Verify Events ==="
	@EVENTS=$$($(KUBECTL) get events -n $(TEST_NAMESPACE) --field-selector reason=ScanCompleted -o jsonpath='{.items}' 2>/dev/null); \
	if [ "$$EVENTS" = "[]" ] || [ -z "$$EVENTS" ]; then \
		echo "FAIL: No ScanCompleted event found"; exit 1; \
	else \
		echo "PASS: ScanCompleted event found"; \
	fi
	@echo ""
	@echo "=== Verify Conditions ==="
	@CONDITION=$$($(KUBECTL) get bestpracticescanners test-scanner -n $(TEST_NAMESPACE) -o jsonpath='{.status.conditions[?(@.type=="ScanComplete")].status}' 2>/dev/null); \
	if [ "$$CONDITION" != "True" ]; then \
		echo "FAIL: ScanComplete condition is not True (got: $$CONDITION)"; exit 1; \
	else \
		echo "PASS: ScanComplete condition is True"; \
	fi
	@echo ""
	@echo "=== Verify Metrics ==="
	@$(KUBECTL) port-forward -n $(OPERATOR_NAMESPACE) deployment/bps-operator-controller-manager 18080:8080 &>/dev/null & \
	PF_PID=$$!; \
	sleep 2; \
	METRICS=$$(curl -s http://localhost:18080/metrics 2>/dev/null | grep bps_scans_total || true); \
	kill $$PF_PID 2>/dev/null; wait $$PF_PID 2>/dev/null; \
	if [ -z "$$METRICS" ]; then \
		echo "FAIL: bps_scans_total metric not found"; exit 1; \
	else \
		echo "PASS: Metrics available"; echo "  $$METRICS"; \
	fi

.PHONY: build-image
build-image:
	docker build -t $(IMG) .

.PHONY: push-image
push-image:
	docker push $(IMG)

##@ Installation

.PHONY: install-yaml
install-yaml: manifests ## Generate install.yaml with all resources needed to deploy the operator
	@echo "# bps-operator install manifest" > install.yaml
	@echo "# Generated by: make install-yaml" >> install.yaml
	@echo "# Apply with: kubectl apply -f install.yaml" >> install.yaml
	@for f in config/manager/manager.yaml config/crd/bases/*.yaml config/rbac/*.yaml; do \
		echo "---" >> install.yaml; \
		cat "$$f" >> install.yaml; \
	done
	@echo "Generated install.yaml"

.PHONY: install
install: manifests ## Install CRDs onto the cluster
	$(KUBECTL) apply -f config/crd/bases/

.PHONY: uninstall
uninstall: ## Remove CRDs from the cluster
	$(KUBECTL) delete --ignore-not-found -f config/crd/bases/

.PHONY: deploy
deploy: manifests _ensure-operator-ns ## Deploy the operator (CRDs + RBAC + manager Deployment)
	$(KUBECTL) apply -f config/crd/bases/
	$(KUBECTL) apply -f config/rbac/
	$(KUBECTL) apply -f config/manager/

.PHONY: undeploy
undeploy: ## Remove the operator from the cluster
	$(KUBECTL) delete --ignore-not-found -f config/manager/
	$(KUBECTL) delete --ignore-not-found -f config/rbac/
	$(KUBECTL) delete --ignore-not-found -f config/crd/bases/

##@ Helpers

# Helper: ensure the operator namespace exists with required privileges for the probe DaemonSet
.PHONY: _ensure-operator-ns
_ensure-operator-ns:
	@$(KUBECTL) create namespace $(OPERATOR_NAMESPACE) --dry-run=client -o yaml | $(KUBECTL) apply -f - 2>/dev/null
	@if $(KUBECTL) api-resources --api-group=security.openshift.io 2>/dev/null | grep -q securitycontextconstraints; then \
		$(KUBECTL) label namespace $(OPERATOR_NAMESPACE) \
			security.openshift.io/scc.podSecurityLabelSync=false \
			pod-security.kubernetes.io/enforce=privileged \
			pod-security.kubernetes.io/warn=privileged \
			pod-security.kubernetes.io/audit=privileged --overwrite 2>/dev/null; \
		$(KUBECTL) adm policy add-scc-to-user privileged -z default -n $(OPERATOR_NAMESPACE) 2>/dev/null || true; \
	fi

# Helper: deploy test workloads and prepare namespace (no scanner CR)
.PHONY: _deploy-test-workloads
_deploy-test-workloads: install
	@$(KUBECTL) delete pods -n $(TEST_NAMESPACE) --all --ignore-not-found 2>/dev/null || true
	@$(KUBECTL) delete --ignore-not-found -f config/samples/scanner_bps_test.yaml 2>/dev/null || true
	@$(KUBECTL) delete --ignore-not-found -f config/samples/scanner_bps_test_periodic.yaml 2>/dev/null || true
	$(KUBECTL) apply -f config/samples/test-workloads.yaml
	@if $(KUBECTL) api-resources --api-group=security.openshift.io 2>/dev/null | grep -q securitycontextconstraints; then \
		echo "OpenShift detected — granting privileged SCC to default SA in $(TEST_NAMESPACE)"; \
		$(KUBECTL) adm policy add-scc-to-user privileged -z default -n $(TEST_NAMESPACE); \
	fi
	@echo "Waiting for namespace to be ready..."
	@$(KUBECTL) wait --for=jsonpath='{.status.phase}'=Active namespace/$(TEST_NAMESPACE) --timeout=10s

##@ Scanning

.PHONY: deploy-test
deploy-test: _deploy-test-workloads ## Deploy test workloads only (no scanner CR)
	@echo ""
	@echo "=== Test Workloads Deployed ==="
	@echo "  Namespace:  $(TEST_NAMESPACE)"
	@echo "  Pods:       good-pod (compliant), bad-pod (non-compliant)"
	@echo "  Services:   good-clusterip-svc, bad-nodeport-svc"
	@echo ""
	@echo "Next steps:"
	@echo "  1. Run a scan:    make deploy-scan  OR  make deploy-periodic-scan"
	@echo "  2. View results:  make show-results"

.PHONY: deploy-scan
deploy-scan: deploy _deploy-test-workloads ## Deploy operator, run one-shot scan, show results
	@echo "Waiting for operator to be ready..."
	@$(KUBECTL) rollout status deployment/bps-operator-controller-manager -n $(OPERATOR_NAMESPACE) --timeout=120s
	$(KUBECTL) apply -f config/samples/scanner_bps_test.yaml
	@echo ""
	@echo "=== One-Shot Scan ==="
	@echo "  Namespace:  $(TEST_NAMESPACE)"
	@echo ""
	@echo "Waiting for scan to complete..."
	@for i in $$(seq 1 60); do \
		PHASE=$$($(KUBECTL) get bestpracticescanners test-scanner -n $(TEST_NAMESPACE) -o jsonpath='{.status.phase}' 2>/dev/null); \
		if [ "$$PHASE" = "Completed" ]; then break; fi; \
		if [ $$i -eq 60 ]; then echo "Timed out waiting for scan (phase: $$PHASE)"; fi; \
		sleep 2; \
	done
	@echo ""
	@$(MAKE) show-results

.PHONY: deploy-periodic-scan
deploy-periodic-scan: deploy _deploy-test-workloads ## Deploy operator, start periodic scan (5m interval)
	@echo "Waiting for operator to be ready..."
	@$(KUBECTL) rollout status deployment/bps-operator-controller-manager -n $(OPERATOR_NAMESPACE) --timeout=120s
	$(KUBECTL) apply -f config/samples/scanner_bps_test_periodic.yaml
	@echo ""
	@echo "=== Periodic Scan Started ==="
	@echo "  Namespace:  $(TEST_NAMESPACE)"
	@echo "  Interval:   every 5m"
	@echo ""
	@echo "View results:  make show-results"
	@echo "View failures: make show-failures"

.PHONY: undeploy-test
undeploy-test: ## Remove test workloads, scanner, and bps-test namespace
	$(KUBECTL) delete --ignore-not-found -f config/samples/scanner_bps_test_periodic.yaml
	$(KUBECTL) delete --ignore-not-found -f config/samples/scanner_bps_test.yaml
	$(KUBECTL) delete --ignore-not-found -f config/samples/test-workloads.yaml
	@if $(KUBECTL) api-resources --api-group=security.openshift.io 2>/dev/null | grep -q securitycontextconstraints; then \
		$(KUBECTL) adm policy remove-scc-from-user privileged -z default -n $(TEST_NAMESPACE) 2>/dev/null || true; \
	fi

.PHONY: scan
scan: deploy-scan ## Alias for deploy-scan

.PHONY: show-results
show-results: ## Show scan results from the cluster
	@echo "=== Scanner Status ==="
	@$(KUBECTL) get bestpracticescanners -n $(TEST_NAMESPACE) 2>/dev/null || echo "No scanners found"
	@echo ""
	@echo "=== Results ==="
	@$(KUBECTL) get bestpracticeresults -n $(TEST_NAMESPACE) 2>/dev/null || echo "No results found"
	@echo ""
	@echo "=== Summary ==="
	@COMPLIANT=$$($(KUBECTL) get bestpracticeresults -n $(TEST_NAMESPACE) -o jsonpath='{.items[?(@.spec.complianceStatus=="Compliant")].metadata.name}' 2>/dev/null | wc -w | tr -d ' '); \
	NONCOMPLIANT=$$($(KUBECTL) get bestpracticeresults -n $(TEST_NAMESPACE) -o jsonpath='{.items[?(@.spec.complianceStatus=="NonCompliant")].metadata.name}' 2>/dev/null | wc -w | tr -d ' '); \
	SKIPPED=$$($(KUBECTL) get bestpracticeresults -n $(TEST_NAMESPACE) -o jsonpath='{.items[?(@.spec.complianceStatus=="Skipped")].metadata.name}' 2>/dev/null | wc -w | tr -d ' '); \
	echo "  Compliant:     $$COMPLIANT"; \
	echo "  NonCompliant:  $$NONCOMPLIANT"; \
	echo "  Skipped:       $$SKIPPED"

.PHONY: show-failures
show-failures: ## Show details for all non-compliant results
	@echo "=== Non-Compliant Checks ==="
	@$(KUBECTL) get bestpracticeresults -n $(TEST_NAMESPACE) \
		-o jsonpath='{range .items[?(@.spec.complianceStatus=="NonCompliant")]}{.spec.checkName}{"\t"}{.spec.reason}{"\n"}{end}' 2>/dev/null \
		| column -t -s $$'\t' || echo "No results found"

.PHONY: show-scan-yaml
show-scan-yaml: ## Print the one-shot scanner CR YAML
	@cat config/samples/scanner_bps_test.yaml

.PHONY: show-periodic-scan-yaml
show-periodic-scan-yaml: ## Print the periodic scanner CR YAML
	@cat config/samples/scanner_bps_test_periodic.yaml

.PHONY: clean
clean: undeploy-test uninstall ## Remove everything: test workloads, CRDs, namespace
	$(KUBECTL) delete namespace $(TEST_NAMESPACE) --ignore-not-found
	@echo "Cleaned up."

##@ Release

.PHONY: release-tag
release-tag: ## Create and push a release tag (usage: make release-tag VERSION=v0.0.4)
	@if [ "$(VERSION)" = "$$(git describe --tags --always --dirty 2>/dev/null || echo dev)" ]; then \
		echo "Error: specify VERSION (e.g., make release-tag VERSION=v0.0.4)"; exit 1; \
	fi
	@if ! echo "$(VERSION)" | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$$'; then \
		echo "Error: VERSION must match vX.Y.Z (got: $(VERSION))"; exit 1; \
	fi
	git tag -a "$(VERSION)" -m "Release $(VERSION)"
	git push origin "$(VERSION)"

##@ Coverage

.PHONY: coverage-html
coverage-html: test
	go tool cover -html=cover.out

##@ Help

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'
