apiVersion: v1
kind: Namespace
metadata:
  name: bps-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bps-operator-controller-manager
  namespace: bps-operator-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bps-operator-controller-manager
  namespace: bps-operator-system
  labels:
    app.kubernetes.io/name: bps-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bps-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bps-operator
    spec:
      serviceAccountName: bps-operator-controller-manager
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
        - name: manager
          image: quay.io/bapalm/bps-operator:latest
          args:
            - --operator-namespace=bps-operator-system
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: health
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
